### PR TITLE
feat: add mentor Srijan R Shetty

### PR DESCRIPTION
**Pull request by srijanshetty**

### CODE REVIEW

**Comment by srijanshetty** [comment]
bump.

**Comment by tanaypratap** [comment]
Thanks for the bump Srijan. I'll check your profile and reply soon. 
Had missed the PR somehow. Pardon me for that.

**Comment by srijanshetty** [comment]
No issues @tanaypratap

**Comment by tanaypratap** [comment]
Hey @srijanshetty I was unable to find any previous speaking experience. Have you given any talk in any of the confs/meetups? Would this be your first speaking arrangement?
If that's the case, I would suggest you take up a small group at first. 
Please don't mind, I am just trying to look out for both sides.

**Comment by tanaypratap** [comment]
Also, welcome to the club Srijan! Good to have you here.

**Comment by srijanshetty** [comment]
@tanaypratap: I've never done a public speaking assignment but have plenty experience taking privates sessions. I intend to take smaller groups to begin with and get the feedback before taking on anything big.

**Pull request merged**
